In [270]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [271]:
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv('u.user', sep='|', names=u_cols, encoding = "ISO-8859-1")

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('u.data', sep='\t', names=r_cols, encoding = "ISO-8859-1")

m_cols = ['movie_id', 'title', 'release_date', 'video_release_date', 'imdb_url']
movies = pd.read_csv('u.item', sep='|', names=m_cols, usecols=range(5), encoding = "ISO-8859-1")

#表格合并，笛卡尔积
movie_ratings = pd.merge(movies, ratings)
lens = pd.merge(movie_ratings, users)
lens

,movie_id,title,release_date,video_release_date,imdb_url,user_id,rating,unix_timestamp,age,sex,occupation,zip_code
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,308,4,887736532,60,M,retired,95076
1,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,308,5,887737890,60,M,retired,95076
2,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),308,4,887739608,60,M,retired,95076
3,7,Twelve Monkeys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Twelve%20Monk...,308,4,887738847,60,M,retired,95076
4,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),308,5,887736696,60,M,retired,95076
5,9,Dead Man Walking (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Dead%20Man%20...,308,4,887737194,60,M,retired,95076
6,11,Seven (Se7en) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995),308,5,887737837,60,M,retired,95076
7,12,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...,308,5,887737243,60,M,retired,95076
8,15,Mr. Holland's Opus (1995),29-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Mr.%20Holland...,308,3,887739426,60,M,retired,95076
9,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...,308,4,887739056,60,M,retired,95076
10,19,Antonia's Line (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Antonia%20(1995),308,3,887737383,60,M,retired,95076
11,21,Muppet Treasure Island (1996),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Muppet%20Trea...,308,3,887740729,60,M,retired,95076
12,22,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...,308,4,887737647,60,M,retired,95076
13,23,Taxi Driver (1976),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Taxi%20Driver...,308,5,887737293,60,M,retired,95076
14,24,Rumble in the Bronx (1995),23-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Hong%20Faan%2...,308,4,887738057,60,M,retired,95076
15,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",308,4,887740649,60,M,retired,95076
16,28,Apollo 13 (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Apollo%2013%2...,308,3,887737036,60,M,retired,95076
17,30,Belle de jour (1967),01-Jan-1967,NaN,http://us.imdb.com/M/title-exact?Belle%20de%20...,308,4,887738933,60,M,retired,95076
18,31,Crimson Tide (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Crimson%20Tid...,308,3,887739472,60,M,retired,95076
19,32,Crumb (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Crumb%20(1994),308,5,887737432,60,M,retired,95076
20,42,Clerks (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Clerks%20(1994),308,4,887738191,60,M,retired,95076
21,44,Dolores Claiborne (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Dolores%20Cla...,308,4,887740451,60,M,retired,95076
22,45,Eat Drink Man Woman (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Yinshi%20Nan%...,308,4,887736843,60,M,retired,95076
23,47,Ed Wood (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Ed%20Wood%20(...,308,4,887738933,60,M,retired,95076
24,48,Hoop Dreams (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Hoop%20Dreams...,308,4,887736880,60,M,retired,95076
25,49,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),308,3,887740833,60,M,retired,95076
26,50,Star Wars (1977),01-Jan-1977,NaN,http://us.imdb.com/M/title-exact?Star%20Wars%2...,308,5,887737431,60,M,retired,95076
27,54,Outbreak (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Outbreak%20(1...,308,2,887740254,60,M,retired,95076
28,55,"Professional, The (1994)",01-Jan-1994,NaN,http://us.imdb.com/Title?L%E9on+(1994),308,3,887738760,60,M,retired,95076
29,56,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,308,5,887736924,60,M,retired,95076
...,...,...,...,...,...,...,...,...,...,...,...,...
99970,332,Kiss the Girls (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kiss+the+Girl...,631,3,888465180,18,F,student,38866
99971,334,U Turn (1997),01-Jan-1997,NaN,http://us.imdb.com/Title?U+Turn+(1997),631,2,888464941,18,F,student,38866
99972,338,Bean (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Bean+(1997),631,2,888465299,18,F,student,38866
99973,346,Jackie Brown (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,631,4,888465004,18,F,student,38866
99974,682,I Know What You Did Last Summer (1997),17-Oct-1997,NaN,http://us.imdb.com/M/title-exact?I+Know+What+Y...,631,2,888465247,18,F,student,38866
99975,873,Picture Perfect (1997),01-Aug-1997,NaN,http://us.imdb.com/M/title-exact?Picture+Perfe...,631,2,888465084,18,F,student,38866
99976,877,Excess Baggage (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Excess+Baggag...,631,2,888465131,18,F,student,38866
99977,886,"Life Less Ordinary, A (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Life+Less+Ord...,631,4,888465216,18,F,student,38866
99978,1527,Senseless (1998),09-Jan-1998,NaN,http://us.imdb.com/M/title-exact?imdb-title-12...,631,2,888465351,18,F,student,38866
99979,272,Good Will Hunting (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,729,4,893286638,19,M,student,56567
99980,288,Scream (1996),20-Dec-1996,NaN,http://us.imdb.com/M/title-exact?Scream%20(1996),729,2,893286261,19,M,student,56567
99981,294,Liar Liar (1997),21-Mar-1997,NaN,http://us.imdb.com/Title?Liar+Liar+(1997),729,2,893286338,19,M,student,56567
99982,300,Air Force One (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Air+Force+One...,729,4,893286638,19,M,student,56567
99983,310,"Rainmaker, The (1997)",01-Jan-1997,NaN,"http://us.imdb.com/M/title-exact?Rainmaker,+Th...",729,3,893286204,19,M,student,56567
99984,313,Titanic (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-12...,729,3,893286638,19,M,student,56567
99985,322,Murder at 1600 (1997),18-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Murder%20at%2...,729,4,893286637,19,M,student,56567
99986,328,Conspiracy Theory (1997),08-Aug-1997,NaN,http://us.imdb.com/M/title-exact?Conspiracy+Th...,729,3,893286638,19,M,student,56567
99987,333,"Game, The (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Game%2C+The+(...,729,4,893286638,19,M,student,56567
99988,338,Bean (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Bean+(1997),729,1,893286373,19,M,student,56567
99989,346,Jackie Brown (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,729,1,893286168,19,M,student,56567
99990,354,"Wedding Singer, The (1998)",13-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Wedding+Singe...,729,5,893286637,19,M,student,56567
99991,362,Blues Brothers 2000 (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Blues+Brother...,729,4,893286637,19,M,student,56567
99992,683,Rocket Man (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Rocket+Man+(1...,729,2,893286511,19,M,student,56567
99993,689,"Jackal, The (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Jackal%2C+The...,729,4,893286638,19,M,student,56567
99994,690,Seven Years in Tibet (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Seven+Years+i...,729,2,893286149,19,M,student,56567
99995,748,"Saint, The (1997)",14-Mar-1997,NaN,http://us.imdb.com/M/title-exact?Saint%2C%20Th...,729,4,893286638,19,M,student,56567
99996,751,Tomorrow Never Dies (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-12...,729,3,893286338,19,M,student,56567
99997,879,"Peacemaker, The (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Peacemaker%2C...,729,3,893286299,19,M,student,56567
99998,894,Home Alone 3 (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,729,1,893286511,19,M,student,56567
99999,901,Mr. Magoo (1997),25-Dec-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,729,1,893286491,19,M,student,56567

In [272]:
#观察详情
lens.groupby('sex').size()

sex
F    25740
M    74260
dtype: int64

In [273]:
#观察详情
lens.groupby('sex').agg({'rating': [np.size, np.mean]})

    rating
      size      mean
sex
F    25740  3.531507
M    74260  3.529289

In [274]:
#过滤杂项
#取投票数大于100的，不然若仅有的男女两票分别为0分与5分，则必定是分歧最大的项，需过滤
at_least100 = lens.groupby('movie_id').size()
at_least100 = at_least100[at_least100 > 100]
lens.set_index('movie_id', inplace=True)
print at_least100.head(20)

movie_id
1     452
2     131
4     209
7     392
8     219
9     299
11    236
12    267
13    184
14    183
15    293
22    297
23    182
24    174
25    293
28    276
29    114
31    154
38    120
42    148
dtype: int64

In [275]:
#行选择
#MultiIndex
by_sex = lens.ix[at_least100.index].groupby(['title', 'sex'])
by_sex = by_sex.rating.mean()
by_sex
#Reshaping

title                                                     sex
101 Dalmatians (1996)                                     F      3.116279
                                                          M      2.772727
12 Angry Men (1957)                                       F      4.269231
                                                          M      4.363636
2001: A Space Odyssey (1968)                              F      3.491228
                                                          M      4.103960
Absolute Power (1997)                                     F      3.451613
                                                          M      3.343750
Abyss, The (1989)                                         F      3.814815
                                                          M      3.540323
Ace Ventura: Pet Detective (1994)                         F      3.105263
                                                          M      3.035714
Adventures of Priscilla, Queen of the Desert, The (1994)  F      3.659091
                                                          M      3.552239
African Queen, The (1951)                                 F      4.000000
                                                          M      4.245614
Air Force One (1997)                                      F      3.690476
                                                          M      3.606557
Aladdin (1992)                                            F      3.949153
                                                          M      3.762500
Alien (1979)                                              F      3.660714
                                                          M      4.123404
Alien: Resurrection (1997)                                F      2.875000
                                                          M      3.150000
Aliens (1986)                                             F      3.672727
                                                          M      4.013100
Amadeus (1984)                                            F      4.038961
                                                          M      4.211055
American President, The (1995)                            F      3.744681
                                                          M      3.581197
                                                                   ...
Usual Suspects, The (1995)                                F      4.333333
                                                          M      4.399061
Vertigo (1958)                                            F      4.073171
                                                          M      4.304348
Volcano (1997)                                            F      3.092593
                                                          M      2.715152
Wag the Dog (1997)                                        F      3.315789
                                                          M      3.585859
Waterworld (1995)                                         F      2.263158
                                                          M      2.927711
Welcome to the Dollhouse (1995)                           F      3.800000
                                                          M      3.695122
What's Eating Gilbert Grape (1993)                        F      3.666667
                                                          M      3.481013
When Harry Met Sally... (1989)                            F      3.988506
                                                          M      3.876847
While You Were Sleeping (1995)                            F      3.637931
                                                          M      3.500000
William Shakespeare's Romeo and Juliet (1996)             F      3.714286
                                                          M      3.535211
Willy Wonka and the Chocolate Factory (1971)              F      3.752688
                                                          M      3.583691
Wizard of Oz, The (1939)                                  F      4.159420
                                                          M      4.045198
Wrong Trousers, The (1993)                                F      4.444444
                                                          M      4.472527
Young Frankenstein (1974)                                 F      4.023810
                                                          M      3.924051
Young Guns (1988)                                         F      3.230769
                                                          M      3.204545
Name: rating, dtype: float64

In [276]:
by_sex = by_sex.unstack(1) 
#取绝对值
by_sex['diff'] = abs(by_sex['F'] - by_sex['M'])
by_sex

sex,F,M,diff
title,,,
101 Dalmatians (1996),3.116279,2.772727,0.343552
12 Angry Men (1957),4.269231,4.363636,0.094406
2001: A Space Odyssey (1968),3.491228,4.103960,0.612732
Absolute Power (1997),3.451613,3.343750,0.107863
"Abyss, The (1989)",3.814815,3.540323,0.274492
Ace Ventura: Pet Detective (1994),3.105263,3.035714,0.069549
"Adventures of Priscilla, Queen of the Desert, The (1994)",3.659091,3.552239,0.106852
"African Queen, The (1951)",4.000000,4.245614,0.245614
Air Force One (1997),3.690476,3.606557,0.083919
Aladdin (1992),3.949153,3.762500,0.186653
Alien (1979),3.660714,4.123404,0.462690
Alien: Resurrection (1997),2.875000,3.150000,0.275000
Aliens (1986),3.672727,4.013100,0.340373
Amadeus (1984),4.038961,4.211055,0.172094
"American President, The (1995)",3.744681,3.581197,0.163484
Amistad (1997),3.882353,3.844444,0.037908
Annie Hall (1977),4.000000,3.882353,0.117647
Apocalypse Now (1979),3.897436,4.076923,0.179487
Apollo 13 (1995),4.000000,3.909953,0.090047
Apt Pupil (1998),3.909091,4.172414,0.263323
Army of Darkness (1993),3.153846,3.466019,0.312173
Arsenic and Old Lace (1944),4.228571,4.012500,0.216071
As Good As It Gets (1997),4.107143,4.226190,0.119048
Austin Powers: International Man of Mystery (1997),3.000000,3.316832,0.316832
Babe (1995),4.050000,3.974843,0.075157
Back to the Future (1985),3.766667,3.857692,0.091026
Basic Instinct (1992),3.363636,3.189873,0.173763
Batman (1989),3.487805,3.412500,0.075305
Batman Forever (1995),3.173913,2.538462,0.635452
Batman Returns (1992),2.880000,2.641026,0.238974
...,...,...,...
Titanic (1997),4.278846,4.231707,0.047139
To Kill a Mockingbird (1962),4.347826,4.266667,0.081159
Tombstone (1993),3.818182,3.627907,0.190275
Tomorrow Never Dies (1997),3.368421,3.443662,0.075241
Top Gun (1986),3.583333,3.453488,0.129845
Toy Story (1995),3.789916,3.909910,0.119994
Trainspotting (1996),3.820000,3.900000,0.080000
True Lies (1994),3.500000,3.579268,0.079268
True Romance (1993),3.000000,3.727273,0.727273
"Truth About Cats & Dogs, The (1996)",3.690722,3.371429,0.319293
Twelve Monkeys (1995),3.560976,3.861290,0.300315
Twister (1996),3.253012,3.200000,0.053012
Ulee's Gold (1997),3.656250,3.696078,0.039828
Under Siege (1992),3.166667,3.311321,0.144654
Unforgiven (1992),3.441176,3.966216,0.525040
"Usual Suspects, The (1995)",4.333333,4.399061,0.065728
Vertigo (1958),4.073171,4.304348,0.231177
Volcano (1997),3.092593,2.715152,0.377441
Wag the Dog (1997),3.315789,3.585859,0.270069
Waterworld (1995),2.263158,2.927711,0.664553
Welcome to the Dollhouse (1995),3.800000,3.695122,0.104878
What's Eating Gilbert Grape (1993),3.666667,3.481013,0.185654
When Harry Met Sally... (1989),3.988506,3.876847,0.111658
While You Were Sleeping (1995),3.637931,3.500000,0.137931
William Shakespeare's Romeo and Juliet (1996),3.714286,3.535211,0.179074
Willy Wonka and the Chocolate Factory (1971),3.752688,3.583691,0.168997
"Wizard of Oz, The (1939)",4.159420,4.045198,0.114223
"Wrong Trousers, The (1993)",4.444444,4.472527,0.028083
Young Frankenstein (1974),4.023810,3.924051,0.099759
Young Guns (1988),3.230769,3.204545,0.026224

In [277]:
least_diff = by_sex.sort_values(by = 'diff')
least_diff[:5]
#least_diff.index
#least_diff.info()

sex                                     F         M      diff
title
Return of the Jedi (1983)        4.008065  4.007833  0.000232
Firm, The (1993)                 3.277778  3.278261  0.000483
Fish Called Wanda, A (1988)      3.784615  3.785714  0.001099
Shining, The (1980)              3.823529  3.825806  0.002277
Long Kiss Goodnight, The (1996)  3.466667  3.471429  0.004762

In [278]:
most_diff = by_sex.sort_values(by = 'diff', ascending=False)
most_diff[:5]

sex                                            F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.187500  3.950413  0.762913
First Wives Club, The (1996)            3.491525  2.742574  0.748951
True Romance (1993)                     3.000000  3.727273  0.727273
Reservoir Dogs (1992)                   3.433333  4.127119  0.693785
Waterworld (1995)                       2.263158  2.927711  0.664553